name: Playwright Tests & Auto Merge

on:
  push:
    branches: ["test-ci", "master"]

permissions:
  contents: write
  pull-requests: write  

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with Allure
        run: npx playwright test --reporter=line,allure-playwright

      - name: Install allure-commandline
        run: npm install -D allure-commandline

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Create PR from test-ci to master
      - name: Create Pull Request to master
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          title: "Auto merge from test-ci to master"
          body: "This PR was automatically created after successful tests."
          labels: auto-merge
          branch-suffix: timestamp   # Tạo nhánh mới, tránh trùng với test-ci

      # Auto merge PR only if it was created
      - name: Merge PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
